### ISSUE TITLE
서비스 처리에 실패했습니다. 오류

### ISSUE THREAD

**Issue by doteka** [leegeunhyeok/school-kr#10]
예제에 있는
const result = await school.search(School.Region.GYEONGGI, '광명경영회계고')
school.init(School.Type.HIGH, School.Region.GYEONGGI, result[0].schoolCode) 이것을

const result = await school.search(School.Region.KANGWON, '양구고등학교')
school.init(School.Type.HIGH, School.Region.KANGWON, 'K100000454') 이렇게 바꿨는데
(node:62904) UnhandledPromiseRejectionWarning: Error: 서비스 처리에 실패했습니다.

    at /Users/mac/Desktop/programing/nodeJS/node_modules/school-kr/dist/school.js:137:17
    at process._tickCallback (internal/process/next_tick.js:68:7)

이런 오류가 나옵니다. 혹시 API오류인가요? 제 개발환경 문제인가요??

**Comment by leegeunhyeok** [comment]
[여기](https://github.com/leegeunhyeok/school-kr/blob/10dcf1a7d49d306d4678d0be0e734b2efaacc577/src/core/index.js#L71)에서 잘못된 코드가 발견된 것으로 확인되었습니다.

각 교육청별로 세션 정보를 가져올 수 있도록 수정한 후 `3.0.1`로 배포하도록 하겠습니다.
감사합니다 :)

**Comment by doteka** [comment]
감사합니다!
