### ISSUE TITLE
영양소 파싱

### ISSUE THREAD

**Issue by minikupa** [leegeunhyeok/school-kr#12]
안녕하세요. 학교앱에서 잘 사용하고 있습니다.
나이스에서 주간식단에서 급식을 가져오면, 영양소(칼로리등)까지 가져올 수 있는데
급식 가져오면서 영양소까지 같이 가져오는건 무리일까요..?

**Comment by leegeunhyeok** [comment]
충분히 가능한 사항입니다. 

관련 데이터를 조회하는 API가 있는지 확인 후 존재하지 않는다면 페이지를 파싱하는 방식으로 구현될 수 있습니다.

검토 후 관련 기능 추가하도록 하겠습니다.

감사합니다😃

**Comment by minikupa** [comment]
넵 감사합니다!
