### ISSUE TITLE
급식이 1년 밀려서 나옵니다.

### ISSUE THREAD

**Issue by minikupa** [leegeunhyeok/school-kr#14]
학교코드는 초등학교, N100000440입니다.

2020년 2월을 파싱 하면, json에는 연도에 2020년, 달에 2월이 찍히며 2019년 2월 급식이 나오고 2021년 2월 급식을 파싱 하면, json에는 연도에 2021년, 달에 2월이 찍히며 2020년 2월 급식이 나옵니다.

버전 업그레이드 전엔 괜찮았는데, 버전 업그레이드 후부터 문제입니다.
다시 예전 버전으로 돌아가니 정상 작동하네요.

나이스도 정상적입니다.

school.getMeal({
          year: req.param('year'),
          month: req.param('month'),
          default: '급식정보가 없습니다.'
        }).then(parse)

**Comment by minikupa** [comment]
제가 주는 앱 개발이라 잘은 모르지만..
getSemesterYear 때문인 듯한데 getSemesterYear이 필요한가요?
주석을 보면 조회 시 1년 낮춰 조회 하라 적혀있는데 오타가 아닌가 싶고..
2월 이하면 1년을 빼는데 그로 인해 2월 이하 시 1년을 더해 조회하면 제자리걸음이 아닌가 싶습니다.

**Comment by leegeunhyeok** [comment]
3.x 버전 확인 결과 1년 낮추어 조회하는 방식은 필요하지 않은것으로 확인되었습니다.

3.x 이하 버전(2.x)에서는 2020년 1월 데이터를 조회하기 위해 -1년 계산 후 진행해야 정상적인 파싱이 가능했으나, API호출 방식으로 변경된 지금 상황으론 불필요한 작업인것으로 확인되었습니다.

3.x으로 업데이트를 진행하여 코어 기능은 모두 코드를 갈아엎었지만, 기본적인 기능 베이스는 2.x 기준으로 옮겨오기만 해서 정확한 테스트를 진행하지 못한 실수입니다.. 죄송합니다 ㅜㅜ😔

해당 문제 해결버전은 3.0.2 버전으로 업데이트 되어 배포될 예정입니다.


감사합니다.
