### ISSUE TITLE
오늘의 학사일정 못봄

### ISSUE THREAD

**Issue by potato179** [leegeunhyeok/school-kr#18]
오늘의 학사일정만 선택해서 보고 싶은데
급식은 오늘의 급식만 볼 수 있는데
학사일정은 그렇게 안되네요... 
설명서에 잘못되어있는거같은데 `calendar.today` 이라고 치면 빈칸이 나오네요..

**Comment by leegeunhyeok** [comment]
아래의 사항을 한 번 확인해주세요

- NEIS 교육청 홈페이지에서 학사일정을 조회했을 때 일정이 존재하는지
  - 교육청이 아닌 자체 학교 홈페이지의 학사일정과는 일치하지 않을 수 있습니다.

문제가 있다면, 검색하신 학교와 날짜(년도/월)을 남겨주세요

감사합니다.

**Comment by potato179** [comment]
> 아래의 사항을 한 번 확인해주세요
> 
> * NEIS 교육청 홈페이지에서 학사일정을 조회했을 때 일정이 존재하는지
>   
>   * 교육청이 아닌 자체 학교 홈페이지의 학사일정과는 일치하지 않을 수 있습니다.
> 
> 문제가 있다면, 검색하신 학교와 날짜(년도/월)을 남겨주세요
> 
> 감사합니다.

급식 정보는 오늘꺼만 따로 출력할 수 있잖아요
학사 일정도 그렇게 할 수는 없을까요??
참고로 나이스 홈페이지에는 정보가 나와있습니다.

**Comment by leegeunhyeok** [comment]
검색한 학교와 날짜(년도, 월)을 알려주시면 확인 후 답변 드리도록 하겠습니다.
