### ISSUE TITLE
다른 지역의 학교 검색 서비스 처리에 실패

### ISSUE THREAD

**Issue by momenthana** [leegeunhyeok/school-kr#19]
<img width="1339" alt="스크린샷 2020-05-24 오후 12 37 43" src="https://user-images.githubusercontent.com/59823089/82745131-aae80900-9dbb-11ea-805b-14a7cb0a0caa.png">
같은 지역을 연이어 시도하는 경우에는 문제가 없으나 연이어 다른 지역의 학교를 검색하는 경우 문제가 발생하였습니다

**Comment by leegeunhyeok** [comment]
늦게 확인한 점 대단히 죄송합니다.

문제 확인 결과, 첫 번째로 지정한 지역(Region) 데이터를 조회한 후
다른 지역 데이터를 조회할 때 발생한 세션 문제임을 파악했습니다.

해당 문제는 [3.1.1](https://github.com/leegeunhyeok/school-kr/releases/tag/3.1.1) 버전으로 수정되어 배포되었습니다.


감사합니다 :)
