### ISSUE TITLE
학교고유코드정보 확인도 가능할지요?

### ISSUE THREAD

**Issue by hyotai** [leegeunhyeok/school-kr#2]
안녕하세요

아주 유용한 프로그램 만들어 주셔서 감사드립니다.

학교 고유코드정보 확인도 가능할지요?

전체 학교 고유코드값을 구하고자 하는데 찾기 어렵네요,, ㅠㅠ

**Comment by leegeunhyeok** [comment]
학교 고유코드의 경우 나이스(NEIS) 코드를 사용하고 있으며 본 라이브러리에서는 이를 제공하진 않습니다.

기존 개발 문서에는 https://www.meatwatch.go.kr를 통해 학교 코드를 검색할 수 있도록 관련 내용이 있었으나, 코드 검색에 로그인 혹은 공인인증서 인증이 필요하도록 변경되에 관련 내용을 제거하였습니다.

현재로서는 구글에 [NEIS 학교코드](https://www.google.com/search?q=NEIS+학교+코드)를 검색하여 이런 저런 방법을 통해 원하시는 학교의 코드를 찾아보셔야 할 것 같습니다.


개선 방안을 찾아 반영해보도록 하겠습니다.

**Comment by leegeunhyeok** [comment]
3.0.0 이후 버전부터 `search` 메소드를 제공합니다.  
이를 통해 학교 정보를(코드 포함) 검색하실 수 있습니다.
