### ISSUE TITLE
업데이트가 지속적으로 진행되고 있나요?

### ISSUE THREAD

**Issue by hgl-215** [leegeunhyeok/school-kr#20]
학교 코드를 파싱하려 하니
직접 구한 학교코드와 School-kr 모듈에서 나온 학교코드가 다르더군요.
확인해본 결과 제가 직접 구한 학교코드가 제대로 된 코드였습니다.

**Comment by leegeunhyeok** [comment]
안녕하세요,

혹시 아래의 정보를 알려주실 수 있나요?
- 학교 코드를 구한 경로
- 학교 정보 및 학교 코드 샘플

현재 school-kr에 구현되어있는 학교 코드 검색 서비스는 공공기관인 `나이스`의 API를 통해 조회한 코드입니다.
나이스 연계 서비스에서만 식별되는 코드이기 때문에, 다른 서비스로부터 수집한 학교 코드와는 다를 수 있습니다.

현재 정확한 확인이 불가능하오니, 요청드린 정보를 제공해주시면 확인해보도록 하겠습니다.


감사합니다.

**Comment by leegeunhyeok** [comment]
추후 요청드린 내용 확인 후 문제가 있을 경우 이슈 열어주세요.

감사합니다.
