### ISSUE TITLE
시간표 가져오는 기능 추가

### ISSUE THREAD

**Issue by minikupa** [leegeunhyeok/school-kr#23]
시간표 가져오는 기능도 추가해주실 수 있으시나요? 다른 앱 보면 자동으로 시간표 가져올 수 있는 것 같더라고요.

**Comment by leegeunhyeok** [comment]
최근부터 공식적인 Open API 서비스가 시작된 것으로 보입니다. [참고](https://open.neis.go.kr/portal/data/dataset/searchDatasetPage.do)

API 키를 발급받은 후 사용할 수 있는 것으로 파악되는데, 본 라이브러리의 코어 기능의 방향과는 조금 다르기 때문에
추가 기능으로 포함하거나, 별도 모듈로 분리하는 방안을 검토해보도록 하겠습니다.


감사합니다 :)
