### ISSUE TITLE
일정이 없다고 출력됩니다.

### ISSUE THREAD

**Issue by JoungChanok** [leegeunhyeok/school-kr#25]
neis에서 학사일정이 정상적으로 출력된 걸 확인한 후 school-kr로 다시 한번 확인해 봤으나 일정이 없다고 출력됩니다.
다른 학교도 마찬가지로 출력되지 않고 있습니다.

**Comment by cjaewon** [comment]
월간일정일 경우 다음 사진과 같이 3월달 이후의 데이터만 가지고 올 수 있는 것 같습니다.
![image](https://user-images.githubusercontent.com/32125218/106600712-21214a00-659e-11eb-8eff-27fad99fde41.png)

연가일정으로 볼 경우에는 2월달 일정까지 확인 할 수 있습니다.
![image](https://user-images.githubusercontent.com/32125218/106600769-31392980-659e-11eb-848b-3c42b1f58cc7.png)

아마도 3월달 이하의 데이터는 저번년의 연간일정을 통해 가져와야 할 것 같습니다.

**Comment by leegeunhyeok** [comment]
이슈 남겨주셔서 감사합니다.

@cjaewon 님의 도움으로 인해 해당 이슈는 3.1.2 버전에서 수정될 예정입니다. 
(변경사항 확인하기: #26 )


배포 이후 버전 업데이트하여 사용 부탁드립니다.
감사합니다 :)
