### ISSUE TITLE
년/월을 선택하면 학사 일정이 안나옵니다

### ISSUE THREAD

**Issue by doteka** [leegeunhyeok/school-kr#6]
2020년 1월 10일 기준으로
calendar 을 이용하여 학사일정을 받아오면 1월 학사일정이 정상적으로 받아옵니다
다만 calendarCustom을 통해 2020년 1월로 설정하면 1월 학사일정이 비어있습니다.
왜 그럴까요
calendarCustom을 통해 다가올 2월, 3월 학사 일정을 받아오는 것도 불가능한가요?

**Comment by doteka** [comment]
앗 감사합니다! 응원하겠습니다!!

**Comment by leegeunhyeok** [comment]
버전 3.0.0이 릴리즈 되었습니다.  
패키지 이름이 `node-school-kr`에서 `school-kr`로 변경되었으니 README.md 참고 부탁드립니다.

**Comment by doteka** [comment]
감사합니다!
